#include "pp_cuda.h"
#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <mma.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
static int fail(char*e,size_t n,const char*s,cudaError_t x=cudaSuccess){if(e&&n)std::snprintf(e,n,"%s%s%s",s,x==cudaSuccess?"":": ",x==cudaSuccess?"":cudaGetErrorString(x));return 0;}static double hms(){timespec t;clock_gettime(CLOCK_MONOTONIC,&t);return t.tv_sec*1e3+t.tv_nsec/1e6;}
struct Cache{const pp_model*m;uint8_t*w;float*feat,*pillar,*scatter,*a,*b,*up0,*up1,*up2,*cat,*shared,*mid,*raw;int32_t*coords;__half*col,*colbig,*wh;};static Cache g;
static const float*dt(const pp_model*m,const char*n,const uint8_t*d){for(uint32_t i=0;i<m->count;i++)if(!std::strcmp(m->records[i].name,n))return reinterpret_cast<const float*>(d+m->records[i].offset);return nullptr;}
__global__ void pfn(const float*f,int np,const float*w,const float*b,float*out){int id=blockIdx.x*blockDim.x+threadIdx.x;if(id>=np*64)return;int p=id/64,o=id%64;float best=0;for(int j=0;j<20;j++){const float*x=f+((size_t)p*20+j)*11;float v=b[o];for(int k=0;k<11;k++)v+=w[o*11+k]*x[k];best=fmaxf(best,v);}out[(size_t)o*np+p]=best;}
__global__ void scatter(const float*x,const int32_t*c,int np,float*y){int id=blockIdx.x*blockDim.x+threadIdx.x;if(id>=np*64)return;int o=id/np,p=id%np,iy=c[(size_t)p*4+2],ix=c[(size_t)p*4+3];y[((size_t)o*512+iy)*512+ix]=x[(size_t)o*np+p];}
__global__ void f2h(const float*x,__half*y,size_t n){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x;if(i<n)y[i]=__float2half(x[i]);}
__global__ void im2col(const float*x,__half*y,int ci,int hi,int wi,int stride,int kernel,int pad,int npad){int ho=(hi+2*pad-kernel)/stride+1,wo=(wi+2*pad-kernel)/stride+1,n=ho*wo,kdim=ci*kernel*kernel;size_t id=(size_t)blockIdx.x*blockDim.x+threadIdx.x,total=(size_t)kdim*npad;if(id>=total)return;int p=id%npad,k=id/npad;if(p>=n){y[id]=__float2half(0);return;}int ox=p%wo,oy=p/wo,ic=k/(kernel*kernel),q=k%(kernel*kernel),iy=oy*stride+q/kernel-pad,ix=ox*stride+q%kernel-pad;float v=0;if((unsigned)iy<(unsigned)hi&&(unsigned)ix<(unsigned)wi)v=x[((size_t)ic*hi+iy)*wi+ix];y[id]=__float2half(v);}
__global__ void wmma_conv(const __half*w,const __half*x,float*y,const float*b,int co,int kdim,int n,int npad,int relu){using namespace nvcuda;int mt=blockIdx.y*16,nt=blockIdx.x*16;if(mt>=co||nt>=n)return;wmma::fragment<wmma::matrix_a,16,16,16,__half,wmma::row_major>a;wmma::fragment<wmma::matrix_b,16,16,16,__half,wmma::row_major>v;wmma::fragment<wmma::accumulator,16,16,16,float>c;wmma::fill_fragment(c,0);for(int k=0;k<kdim;k+=16){wmma::load_matrix_sync(a,w+(size_t)mt*kdim+k,kdim);wmma::load_matrix_sync(v,x+(size_t)k*npad+nt,npad);wmma::mma_sync(c,a,v,c);}__shared__ float z[256];wmma::store_matrix_sync(z,c,16,wmma::mem_row_major);__syncthreads();for(int q=threadIdx.x;q<256;q+=32){int r=q/16,s=q%16;if(mt+r<co&&nt+s<n){float t=z[q]+b[mt+r];y[(size_t)(mt+r)*n+nt+s]=relu?fmaxf(t,0):t;}}}
__device__ float wsum(float v){for(int d=16;d;d>>=1)v+=__shfl_down_sync(0xffffffff,v,d);return v;}
__global__ void direct_conv(const float*x,float*y,const float*w,const float*b,int ci,int co,int hi,int wi,int stride,int kernel,int pad,int relu){int lane=threadIdx.x&31,warp=threadIdx.x>>5,ho=(hi+2*pad-kernel)/stride+1,wo=(wi+2*pad-kernel)/stride+1;size_t id=(size_t)blockIdx.x*8+warp,total=(size_t)co*ho*wo;if(id>=total)return;int ox=id%wo,oy=(id/wo)%ho,oc=id/(wo*ho),kk=kernel*kernel;float sum=0;for(int q=lane;q<ci*kk;q+=32){int ic=q/kk,k=q%kk,iy=oy*stride+k/kernel-pad,ix=ox*stride+k%kernel-pad;if((unsigned)iy<(unsigned)hi&&(unsigned)ix<(unsigned)wi)sum+=x[((size_t)ic*hi+iy)*wi+ix]*w[((size_t)oc*ci+ic)*kk+k];}sum=wsum(sum);if(!lane){sum+=b[oc];y[id]=relu?fmaxf(sum,0):sum;}}
__global__ void deconv(const float*x,float*y,const float*w,const float*b,int ci,int co,int hi,int wi,int k){int lane=threadIdx.x&31,warp=threadIdx.x>>5,ho=hi*k,wo=wi*k;size_t id=(size_t)blockIdx.x*8+warp,total=(size_t)co*ho*wo;if(id>=total)return;int ox=id%wo,oy=(id/wo)%ho,oc=id/(wo*ho),ix=ox/k,iy=oy/k,kx=ox%k,ky=oy%k;float s=0;for(int ic=lane;ic<ci;ic+=32)s+=x[((size_t)ic*hi+iy)*wi+ix]*w[((size_t)ic*co+oc)*k*k+ky*k+kx];s=wsum(s);if(!lane)y[id]=fmaxf(s+b[oc],0);}
static int launch(const pp_model*m,const uint8_t*dw,const char*name,const float*x,float*y,int ci,int co,int hi,int wi,int stride,int kernel,int pad,int relu,__half*col,__half*wh,int precise,char*e,size_t cap){char nw[48],nb[48];std::snprintf(nw,sizeof nw,"%s.weight",name);std::snprintf(nb,sizeof nb,"%s.bias",name);const float*wt=dt(m,nw,dw),*bias=dt(m,nb,dw);if(!wt||!bias)return fail(e,cap,name);int ho=(hi+2*pad-kernel)/stride+1,wo=(wi+2*pad-kernel)/stride+1,n=ho*wo,kdim=ci*kernel*kernel;if(precise){size_t z=(size_t)co*n;direct_conv<<<(z+7)/8,256>>>(x,y,wt,bias,ci,co,hi,wi,stride,kernel,pad,relu);}else{int npad=(n+15)&~15;size_t wn=(size_t)co*kdim,cn=(size_t)kdim*npad;f2h<<<(wn+255)/256,256>>>(wt,wh,wn);im2col<<<(cn+255)/256,256>>>(x,col,ci,hi,wi,stride,kernel,pad,npad);dim3 grid((npad+15)/16,(co+15)/16);wmma_conv<<<grid,32>>>(wh,col,y,bias,co,kdim,n,npad,relu);}return 1;}
extern "C" int pp_cuda_available(char*e,size_t n){int c=0;cudaError_t x=cudaGetDeviceCount(&c);return x==cudaSuccess&&c?1:fail(e,n,"CUDA unavailable",x);}
extern "C" int pp_infer_cuda(const pp_model*m,const pp_pillars*p,pp_raw_output*out,pp_profile*pr,char*e,size_t cap){if(!pp_cuda_available(e,cap)||!out||!out->data)return 0;pp_profile local{};if(!pr)pr=&local;*pr={};double begin=hms();int precise=std::getenv("PP_CUDA_PRECISE")&&std::strcmp(std::getenv("PP_CUDA_PRECISE"),"0");cudaError_t ce;
 #define MA(v,n) do{if((ce=cudaMalloc((void**)&v,n))!=cudaSuccess)return fail(e,cap,"cudaMalloc",ce);}while(0)
 if(!g.w){g.m=m;MA(g.w,m->data_bytes);MA(g.feat,(size_t)30000*20*11*4);MA(g.coords,(size_t)30000*4*4);MA(g.pillar,(size_t)64*30000*4);MA(g.scatter,(size_t)64*512*512*4);MA(g.a,(size_t)64*256*256*4);MA(g.b,(size_t)64*256*256*4);size_t up=(size_t)128*128*128;MA(g.up0,up*4);MA(g.up1,up*4);MA(g.up2,up*4);MA(g.cat,(size_t)384*128*128*4);MA(g.shared,(size_t)64*128*128*4);MA(g.mid,(size_t)64*128*128*4);MA(g.raw,out->floats*4);MA(g.col,(size_t)576*256*256*sizeof(__half));MA(g.wh,(size_t)256*256*9*sizeof(__half));cudaMemcpy(g.w,m->data,m->data_bytes,cudaMemcpyHostToDevice);}if(g.m!=m)return fail(e,cap,"CUDA model changed");
 if(!g.colbig)MA(g.colbig,(size_t)3456*128*128*sizeof(__half));cudaMemcpy(g.feat,p->features,(size_t)p->pillar_count*20*11*4,cudaMemcpyHostToDevice);cudaMemcpy(g.coords,p->coords,(size_t)p->pillar_count*4*4,cudaMemcpyHostToDevice);cudaMemset(g.scatter,0,(size_t)64*512*512*4);double pt=hms();pfn<<<(p->pillar_count*64+255)/256,256>>>(g.feat,p->pillar_count,dt(m,"pfn.weight",g.w),dt(m,"pfn.bias",g.w),g.pillar);scatter<<<(p->pillar_count*64+255)/256,256>>>(g.pillar,g.coords,p->pillar_count,g.scatter);cudaDeviceSynchronize();pr->pfn_ms=hms()-pt;double bt=hms();const int counts[3]={4,6,6},cos[3]={64,128,256};const float*cur=g.scatter;float*dst=g.a;int ci=64,h=512,w=512;
 for(int s=0;s<3;s++)for(int l=0;l<counts[s];l++){char n[40];std::snprintf(n,sizeof n,"backbone.%d.%d",s,l);int st=l?1:2;if(!launch(m,g.w,n,cur,dst,ci,cos[s],h,w,st,3,1,1,g.col,g.wh,precise,e,cap))return 0;h/=st;w/=st;ci=cos[s];cur=dst;dst=dst==g.a?g.b:g.a;if(l==counts[s]-1){char nw[48],nb[48];std::snprintf(nw,sizeof nw,"deblock.%d.weight",s);std::snprintf(nb,sizeof nb,"deblock.%d.bias",s);if(s==0){if(!launch(m,g.w,"deblock.0",cur,g.up0,64,128,256,256,2,2,0,1,g.col,g.wh,precise,e,cap))return 0;}else{int k=s==1?1:2,ici=s==1?128:256;float*u=s==1?g.up1:g.up2;size_t z=(size_t)128*h*k*w*k;deconv<<<(z+7)/8,256>>>(cur,u,dt(m,nw,g.w),dt(m,nb,g.w),ici,128,h,w,k);}}}
 size_t up=(size_t)128*128*128;cudaMemcpy(g.cat,g.up0,up*4,cudaMemcpyDeviceToDevice);cudaMemcpy(g.cat+up,g.up1,up*4,cudaMemcpyDeviceToDevice);cudaMemcpy(g.cat+2*up,g.up2,up*4,cudaMemcpyDeviceToDevice);if(!launch(m,g.w,"shared",g.cat,g.shared,384,64,128,128,1,3,1,1,g.colbig,g.wh,precise,e,cap))return 0;cudaDeviceSynchronize();pr->backbone_ms=hms()-bt;double ht=hms();static const char*bn[6]={"cls","reg","height","size","angle","velo"};
 for(int hd=0;hd<6;hd++)for(int br=0;br<6;br++){char n[48];std::snprintf(n,sizeof n,"head.%d.%s.mid",hd,bn[br]);if(!launch(m,g.w,n,g.shared,g.mid,64,64,128,128,1,3,1,1,g.col,g.wh,precise,e,cap))return 0;std::snprintf(n,sizeof n,"head.%d.%s.out",hd,bn[br]);float*host=pp_output_branch(out,hd,br);float*dev=g.raw+(host-out->data);if(!launch(m,g.w,n,g.mid,dev,64,pp_branch_channels(hd,br),128,128,1,3,1,0,g.col,g.wh,precise,e,cap))return 0;}
 if((ce=cudaDeviceSynchronize())!=cudaSuccess)return fail(e,cap,"CUDA inference",ce);pr->heads_ms=hms()-ht;cudaMemcpy(out->data,g.raw,out->floats*4,cudaMemcpyDeviceToHost);pr->total_ms=hms()-begin;pr->workspace_bytes=(size_t)300*1024*1024;return 1;}
