#include "pp_cuda.h"
#include <cuda_runtime.h>
#include <cuda_fp16.h>
#include <mma.h>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <ctime>
#include <cmath>
static int fail(char*e,size_t n,const char*s,cudaError_t x=cudaSuccess){if(e&&n)std::snprintf(e,n,"%s%s%s",s,x==cudaSuccess?"":": ",x==cudaSuccess?"":cudaGetErrorString(x));return 0;}static double hms(){timespec t;clock_gettime(CLOCK_MONOTONIC,&t);return t.tv_sec*1e3+t.tv_nsec/1e6;}
enum{COMPACT_PER_CLASS=65536};
static_assert(sizeof(pp_compact_candidate)==52,"compact candidate ABI");
struct Cache{const pp_model*m;uint8_t*w;__half*hw;float*feat,*pillar,*scatter,*a,*b,*up0,*up1,*up2,*cat,*shared,*mid,*raw;int32_t*coords,*compact_count;__half*col,*colbig;pp_compact_candidate*compact;size_t raw_floats;cudaEvent_t event[4];};static Cache g;
static size_t branch_offset(int h,int b){size_t off=0,hw=(size_t)PP_OUT_H*PP_OUT_W;for(int i=0;i<h;i++)for(int j=0;j<6;j++)off+=(size_t)pp_branch_channels(i,j)*hw;for(int j=0;j<b;j++)off+=(size_t)pp_branch_channels(h,j)*hw;return off;}
static const float*dt(const pp_model*m,const char*n,const uint8_t*d){for(uint32_t i=0;i<m->count;i++)if(!std::strcmp(m->records[i].name,n))return reinterpret_cast<const float*>(d+m->records[i].offset);return nullptr;}
static const __half*ht(const pp_model*m,const char*n,const __half*d){for(uint32_t i=0;i<m->count;i++)if(!std::strcmp(m->records[i].name,n))return d+m->records[i].offset/sizeof(float);return nullptr;}
__global__ void pfn(const float*f,int np,const float*w,const float*b,float*out){int id=blockIdx.x*blockDim.x+threadIdx.x;if(id>=np*64)return;int p=id/64,o=id%64;float best=0;for(int j=0;j<20;j++){const float*x=f+((size_t)p*20+j)*11;float v=b[o];for(int k=0;k<11;k++)v+=w[o*11+k]*x[k];best=fmaxf(best,v);}out[(size_t)o*np+p]=best;}
__global__ void scatter(const float*x,const int32_t*c,int np,float*y){int id=blockIdx.x*blockDim.x+threadIdx.x;if(id>=np*64)return;int o=id/np,p=id%np,iy=c[(size_t)p*4+2],ix=c[(size_t)p*4+3];y[((size_t)o*512+iy)*512+ix]=x[(size_t)o*np+p];}
__global__ void f2h(const float*x,__half*y,size_t n){size_t i=(size_t)blockIdx.x*blockDim.x+threadIdx.x;if(i<n)y[i]=__float2half(x[i]);}
__global__ void im2col_linear(const float*x,__half*y,int ci,int hi,int wi,int stride,int kernel,int pad,int npad){int ho=(hi+2*pad-kernel)/stride+1,wo=(wi+2*pad-kernel)/stride+1,n=ho*wo,kdim=ci*kernel*kernel;size_t id=(size_t)blockIdx.x*blockDim.x+threadIdx.x,total=(size_t)kdim*npad;if(id>=total)return;int p=id%npad,k=id/npad;if(p>=n){y[id]=__float2half(0);return;}int ox=p%wo,oy=p/wo,ic=k/(kernel*kernel),q=k%(kernel*kernel),iy=oy*stride+q/kernel-pad,ix=ox*stride+q%kernel-pad;float v=0;if((unsigned)iy<(unsigned)hi&&(unsigned)ix<(unsigned)wi)v=x[((size_t)ic*hi+iy)*wi+ix];y[id]=__float2half(v);}
__global__ void im2col_2d(const float*x,__half*y,int hi,int wi,int stride,int kernel,int pad,int n,int npad){int p=blockIdx.x*blockDim.x+threadIdx.x,k=blockIdx.y;if(p>=npad)return;size_t id=(size_t)k*npad+p;if(p>=n){y[id]=__float2half(0);return;}int kk=kernel*kernel,wo=(wi+2*pad-kernel)/stride+1,ox=p%wo,oy=p/wo,ic=k/kk,q=k%kk,iy=oy*stride+q/kernel-pad,ix=ox*stride+q%kernel-pad;float v=0;if((unsigned)iy<(unsigned)hi&&(unsigned)ix<(unsigned)wi)v=x[((size_t)ic*hi+iy)*wi+ix];y[id]=__float2half(v);}
static void launch_im2col(const float*x,__half*y,int ci,int hi,int wi,int stride,int kernel,int pad,int npad){int ho=(hi+2*pad-kernel)/stride+1,wo=(wi+2*pad-kernel)/stride+1,n=ho*wo,kdim=ci*kernel*kernel;static int legacy=-1;if(legacy<0)legacy=std::getenv("PP_CUDA_LEGACY_IM2COL")!=nullptr;if(legacy){size_t total=(size_t)kdim*npad;im2col_linear<<<(total+255)/256,256>>>(x,y,ci,hi,wi,stride,kernel,pad,npad);}else{dim3 grid((npad+255)/256,kdim);im2col_2d<<<grid,256>>>(x,y,hi,wi,stride,kernel,pad,n,npad);}}
__global__ void wmma_conv(const __half*w,const __half*x,float*y,const float*b,int co,int kdim,int n,int npad,int relu){using namespace nvcuda;int mt=blockIdx.y*16,nt=blockIdx.x*16;if(mt>=co||nt>=n)return;wmma::fragment<wmma::matrix_a,16,16,16,__half,wmma::row_major>a;wmma::fragment<wmma::matrix_b,16,16,16,__half,wmma::row_major>v;wmma::fragment<wmma::accumulator,16,16,16,float>c;wmma::fill_fragment(c,0);for(int k=0;k<kdim;k+=16){wmma::load_matrix_sync(a,w+(size_t)mt*kdim+k,kdim);wmma::load_matrix_sync(v,x+(size_t)k*npad+nt,npad);wmma::mma_sync(c,a,v,c);}__shared__ float z[256];wmma::store_matrix_sync(z,c,16,wmma::mem_row_major);__syncthreads();for(int q=threadIdx.x;q<256;q+=32){int r=q/16,s=q%16;if(mt+r<co&&nt+s<n){float t=z[q]+b[mt+r];y[(size_t)(mt+r)*n+nt+s]=relu?fmaxf(t,0):t;}}}
__global__ void wmma_conv_implicit(const __half*w,const float*x,float*y,const float*b,int ci,int co,int hi,int wi,int stride,int kernel,int pad,int relu){using namespace nvcuda;int tid=threadIdx.x,warp=tid>>5,lane=tid&31,mt=blockIdx.y*64+warp*16,nt=blockIdx.x*16,ho=(hi+2*pad-kernel)/stride+1,wo=(wi+2*pad-kernel)/stride+1,n=ho*wo,kdim=ci*kernel*kernel;__shared__ __half sv[256],sa[4][256];__shared__ float sz[4][256];wmma::fragment<wmma::matrix_a,16,16,16,__half,wmma::row_major>a;wmma::fragment<wmma::matrix_b,16,16,16,__half,wmma::row_major>v;wmma::fragment<wmma::accumulator,16,16,16,float>c;wmma::fill_fragment(c,0);for(int kb=0;kb<kdim;kb+=16){for(int q=tid;q<256;q+=128){int kr=q>>4,s=q&15,k=kb+kr,p=nt+s,ic=k/(kernel*kernel),tap=k%(kernel*kernel),iy=(p/wo)*stride+tap/kernel-pad,ix=(p%wo)*stride+tap%kernel-pad;float value=0;if(p<n&&(unsigned)iy<(unsigned)hi&&(unsigned)ix<(unsigned)wi)value=x[((size_t)ic*hi+iy)*wi+ix];sv[q]=__float2half(value);}for(int q=tid;q<1024;q+=128){int wm=q>>8,t=q&255,row=blockIdx.y*64+wm*16+(t>>4),k=kb+(t&15);sa[wm][t]=(row<co)?w[(size_t)row*kdim+k]:__float2half(0);}__syncthreads();if(mt<co){wmma::load_matrix_sync(a,sa[warp],16);wmma::load_matrix_sync(v,sv,16);wmma::mma_sync(c,a,v,c);}__syncthreads();}if(mt<co)wmma::store_matrix_sync(sz[warp],c,16,wmma::mem_row_major);__syncthreads();if(mt<co)for(int q=lane;q<256;q+=32){int r=q>>4,s=q&15;if(mt+r<co&&nt+s<n){float t=sz[warp][q]+b[mt+r];y[(size_t)(mt+r)*n+nt+s]=relu?fmaxf(t,0):t;}}}
__device__ float wsum(float v){for(int d=16;d;d>>=1)v+=__shfl_down_sync(0xffffffff,v,d);return v;}
__global__ void direct_conv(const float*x,float*y,const float*w,const float*b,int ci,int co,int hi,int wi,int stride,int kernel,int pad,int relu){int lane=threadIdx.x&31,warp=threadIdx.x>>5,ho=(hi+2*pad-kernel)/stride+1,wo=(wi+2*pad-kernel)/stride+1;size_t id=(size_t)blockIdx.x*8+warp,total=(size_t)co*ho*wo;if(id>=total)return;int ox=id%wo,oy=(id/wo)%ho,oc=id/(wo*ho),kk=kernel*kernel;float sum=0;for(int q=lane;q<ci*kk;q+=32){int ic=q/kk,k=q%kk,iy=oy*stride+k/kernel-pad,ix=ox*stride+k%kernel-pad;if((unsigned)iy<(unsigned)hi&&(unsigned)ix<(unsigned)wi)sum+=x[((size_t)ic*hi+iy)*wi+ix]*w[((size_t)oc*ci+ic)*kk+k];}sum=wsum(sum);if(!lane){sum+=b[oc];y[id]=relu?fmaxf(sum,0):sum;}}
__global__ void deconv(const float*x,float*y,const float*w,const float*b,int ci,int co,int hi,int wi,int k){int lane=threadIdx.x&31,warp=threadIdx.x>>5,ho=hi*k,wo=wi*k;size_t id=(size_t)blockIdx.x*8+warp,total=(size_t)co*ho*wo;if(id>=total)return;int ox=id%wo,oy=(id/wo)%ho,oc=id/(wo*ho),ix=ox/k,iy=oy/k,kx=ox%k,ky=oy%k;float s=0;for(int ic=lane;ic<ci;ic+=32)s+=x[((size_t)ic*hi+iy)*wi+ix]*w[((size_t)ic*co+oc)*k*k+ky*k+kx];s=wsum(s);if(!lane)y[id]=fmaxf(s+b[oc],0);}
__constant__ size_t compact_branch_offset[36];
__global__ void compact_candidates(const float*raw,pp_compact_candidate*out,int32_t*counts,int global,int head,int classes,int local,int anchors,float threshold){size_t id=(size_t)blockIdx.x*blockDim.x+threadIdx.x,total=(size_t)anchors*128*128;if(id>=total)return;int a=id/(128*128);uint32_t p=(uint32_t)(id%(128*128));float logit=raw[compact_branch_offset[head*6]+((size_t)a*classes+local)*128*128+p];if(logit<threshold)return;int slot=atomicAdd(counts+global,1);if(slot>=COMPACT_PER_CLASS)return;pp_compact_candidate*c=out+(size_t)global*COMPACT_PER_CLASS+slot;c->logit=logit;c->position=p;c->head=(uint8_t)head;c->anchor=(uint8_t)a;c->class_id=(uint8_t)global;c->reserved=0;int channel=a*10,prefix=0;for(int q=0;q<10;q++,channel++){for(int br=1;br<6;br++){int mul=br==1?4:br==2?2:br==3?6:4,n=classes*mul;if(channel<prefix+n){c->code[q]=raw[compact_branch_offset[head*6+br]+(size_t)(channel-prefix)*128*128+p];break;}prefix+=n;}prefix=0;}}
static int explicit_heads;
static int use_implicit(){static int enabled=-1;if(enabled<0)enabled=std::getenv("PP_CUDA_EXPLICIT")==nullptr;return enabled&&!explicit_heads;}
static int launch(const pp_model*m,const uint8_t*dw,const __half*dh,const char*name,const float*x,float*y,int ci,int co,int hi,int wi,int stride,int kernel,int pad,int relu,__half*col,int precise,char*e,size_t cap){char nw[48],nb[48];std::snprintf(nw,sizeof nw,"%s.weight",name);std::snprintf(nb,sizeof nb,"%s.bias",name);const float*wt=dt(m,nw,dw),*bias=dt(m,nb,dw);if(!wt||!bias)return fail(e,cap,name);int ho=(hi+2*pad-kernel)/stride+1,wo=(wi+2*pad-kernel)/stride+1,n=ho*wo,kdim=ci*kernel*kernel;if(precise){size_t z=(size_t)co*n;direct_conv<<<(z+7)/8,256>>>(x,y,wt,bias,ci,co,hi,wi,stride,kernel,pad,relu);}else{const __half*wh=ht(m,nw,dh);if(!wh)return fail(e,cap,name);if(use_implicit()){dim3 grid((n+15)/16,(co+63)/64);wmma_conv_implicit<<<grid,128>>>(wh,x,y,bias,ci,co,hi,wi,stride,kernel,pad,relu);}else{int npad=(n+15)&~15;launch_im2col(x,col,ci,hi,wi,stride,kernel,pad,npad);dim3 grid((npad+15)/16,(co+15)/16);wmma_conv<<<grid,32>>>(wh,col,y,bias,co,kdim,n,npad,relu);}}return 1;}
static int launch_precol(const pp_model*m,const uint8_t*dw,const __half*dh,const char*name,const __half*col,float*y,int co,int relu,char*e,size_t cap){char nw[64],nb[64];std::snprintf(nw,sizeof nw,"%s.weight",name);std::snprintf(nb,sizeof nb,"%s.bias",name);const __half*wh=ht(m,nw,dh);const float*bias=dt(m,nb,dw);if(!wh||!bias)return fail(e,cap,name);constexpr int n=128*128,kdim=64*9;dim3 grid(n/16,(co+15)/16);wmma_conv<<<grid,32>>>(wh,col,y,bias,co,kdim,n,n,relu);return 1;}
extern "C" int pp_cuda_available(char*e,size_t n){int c=0;cudaError_t x=cudaGetDeviceCount(&c);return x==cudaSuccess&&c?1:fail(e,n,"CUDA unavailable",x);}
static int infer_cuda_impl(const pp_model*m,const pp_pillars*p,pp_raw_output*out,pp_detections*det,float score_thr,float nms_thr,pp_profile*pr,char*e,size_t cap){if(!pp_cuda_available(e,cap)||(!det&&(!out||!out->data)))return 0;if(m->data_bytes%sizeof(float))return fail(e,cap,"unaligned CUDA model data");pp_profile local{};if(!pr)pr=&local;*pr={};double begin=hms();int precise=std::getenv("PP_CUDA_PRECISE")&&std::strcmp(std::getenv("PP_CUDA_PRECISE"),"0");cudaError_t ce;
 #define MA(v,n) do{if((ce=cudaMalloc((void**)&v,n))!=cudaSuccess)return fail(e,cap,"cudaMalloc",ce);}while(0)
 if(!g.w){g.m=m;for(int h=0;h<6;h++)for(int b=0;b<6;b++)g.raw_floats+=(size_t)pp_branch_channels(h,b)*128*128;MA(g.w,m->data_bytes);MA(g.hw,m->data_bytes/sizeof(float)*sizeof(__half));MA(g.feat,(size_t)30000*20*11*4);MA(g.coords,(size_t)30000*4*4);MA(g.pillar,(size_t)64*30000*4);MA(g.scatter,(size_t)64*512*512*4);MA(g.a,(size_t)64*256*256*4);MA(g.b,(size_t)64*256*256*4);size_t up=(size_t)128*128*128;MA(g.up0,up*4);MA(g.up1,up*4);MA(g.up2,up*4);MA(g.cat,(size_t)384*128*128*4);MA(g.shared,(size_t)64*128*128*4);MA(g.mid,(size_t)64*128*128*4);MA(g.raw,g.raw_floats*4);size_t col_spatial=use_implicit()?(size_t)128*128:(size_t)256*256;MA(g.col,(size_t)576*col_spatial*sizeof(__half));for(int i=0;i<4;i++)if((ce=cudaEventCreate(g.event+i))!=cudaSuccess)return fail(e,cap,"cudaEventCreate",ce);size_t offsets[36];for(int h=0;h<6;h++)for(int b=0;b<6;b++)offsets[h*6+b]=branch_offset(h,b);cudaMemcpyToSymbol(compact_branch_offset,offsets,sizeof(offsets));cudaMemcpy(g.w,m->data,m->data_bytes,cudaMemcpyHostToDevice);f2h<<<(m->data_bytes/sizeof(float)+255)/256,256>>>(reinterpret_cast<const float*>(g.w),g.hw,m->data_bytes/sizeof(float));}if(g.m!=m)return fail(e,cap,"CUDA model changed");
 int sync_stages=std::getenv("PP_CUDA_SYNC_STAGES")!=nullptr;if(!g.colbig){size_t colbig_k=use_implicit()?576:3456;MA(g.colbig,colbig_k*128*128*sizeof(__half));}cudaMemcpy(g.feat,p->features,(size_t)p->pillar_count*20*11*4,cudaMemcpyHostToDevice);cudaMemcpy(g.coords,p->coords,(size_t)p->pillar_count*4*4,cudaMemcpyHostToDevice);cudaMemset(g.scatter,0,(size_t)64*512*512*4);cudaEventRecord(g.event[0]);pfn<<<(p->pillar_count*64+255)/256,256>>>(g.feat,p->pillar_count,dt(m,"pfn.weight",g.w),dt(m,"pfn.bias",g.w),g.pillar);scatter<<<(p->pillar_count*64+255)/256,256>>>(g.pillar,g.coords,p->pillar_count,g.scatter);cudaEventRecord(g.event[1]);if(sync_stages)cudaDeviceSynchronize();const int counts[3]={4,6,6},cos[3]={64,128,256};const float*cur=g.scatter;float*dst=g.a;int ci=64,h=512,w=512;
 for(int s=0;s<3;s++)for(int l=0;l<counts[s];l++){char n[40];std::snprintf(n,sizeof n,"backbone.%d.%d",s,l);int st=l?1:2;if(!launch(m,g.w,g.hw,n,cur,dst,ci,cos[s],h,w,st,3,1,1,g.col,precise,e,cap))return 0;h/=st;w/=st;ci=cos[s];cur=dst;dst=dst==g.a?g.b:g.a;if(l==counts[s]-1){char nw[48],nb[48];std::snprintf(nw,sizeof nw,"deblock.%d.weight",s);std::snprintf(nb,sizeof nb,"deblock.%d.bias",s);if(s==0){if(!launch(m,g.w,g.hw,"deblock.0",cur,g.up0,64,128,256,256,2,2,0,1,g.col,precise,e,cap))return 0;}else{int k=s==1?1:2,ici=s==1?128:256;float*u=s==1?g.up1:g.up2;size_t z=(size_t)128*h*k*w*k;deconv<<<(z+7)/8,256>>>(cur,u,dt(m,nw,g.w),dt(m,nb,g.w),ici,128,h,w,k);}}}
 size_t up=(size_t)128*128*128;cudaMemcpy(g.cat,g.up0,up*4,cudaMemcpyDeviceToDevice);cudaMemcpy(g.cat+up,g.up1,up*4,cudaMemcpyDeviceToDevice);cudaMemcpy(g.cat+2*up,g.up2,up*4,cudaMemcpyDeviceToDevice);if(!launch(m,g.w,g.hw,"shared",g.cat,g.shared,384,64,128,128,1,3,1,1,g.colbig,precise,e,cap))return 0;cudaEventRecord(g.event[2]);if(sync_stages)cudaDeviceSynchronize();static const char*bn[6]={"cls","reg","height","size","angle","velo"};
 explicit_heads=1;if(!precise)launch_im2col(g.shared,g.colbig,64,128,128,1,3,1,128*128);
 for(int hd=0;hd<6;hd++)for(int br=0;br<6;br++){char n[48];std::snprintf(n,sizeof n,"head.%d.%s.mid",hd,bn[br]);if(precise){if(!launch(m,g.w,g.hw,n,g.shared,g.mid,64,64,128,128,1,3,1,1,g.col,1,e,cap))return 0;}else if(!launch_precol(m,g.w,g.hw,n,g.colbig,g.mid,64,1,e,cap))return 0;std::snprintf(n,sizeof n,"head.%d.%s.out",hd,bn[br]);float*dev=g.raw+branch_offset(hd,br);if(!launch(m,g.w,g.hw,n,g.mid,dev,64,pp_branch_channels(hd,br),128,128,1,3,1,0,g.col,precise,e,cap))return 0;}explicit_heads=0;
 cudaEventRecord(g.event[3]);if(sync_stages&&(ce=cudaDeviceSynchronize())!=cudaSuccess)return fail(e,cap,"CUDA inference",ce);if(det){if(!(score_thr>0&&score_thr<1))return fail(e,cap,"invalid score threshold");if(!g.compact_count)MA(g.compact_count,10*sizeof(*g.compact_count));if(!g.compact)MA(g.compact,(size_t)10*COMPACT_PER_CLASS*sizeof(*g.compact));if((ce=cudaMemset(g.compact_count,0,10*sizeof(*g.compact_count)))!=cudaSuccess)return fail(e,cap,"compact count reset",ce);static const int gh[10]={0,1,1,2,2,3,4,4,5,5},gl[10]={0,0,1,0,1,0,0,1,0,1};float threshold=std::log(score_thr/(1-score_thr));for(int global=0;global<10;global++){int h=gh[global],classes=pp_head_classes(h),anchors=2*classes,total=anchors*128*128;compact_candidates<<<(total+255)/256,256>>>(g.raw,g.compact,g.compact_count,global,h,classes,gl[global],anchors,threshold);}int32_t counts[10];if((ce=cudaMemcpy(counts,g.compact_count,sizeof(counts),cudaMemcpyDeviceToHost))!=cudaSuccess)return fail(e,cap,"compact count copy",ce);size_t total=0;for(int i=0;i<10;i++){if(counts[i]<0||counts[i]>COMPACT_PER_CLASS)return fail(e,cap,"invalid compact candidate count");total+=(size_t)counts[i];}pp_compact_candidate*host=(pp_compact_candidate*)std::malloc((total?total:1)*sizeof(*host));if(!host)return fail(e,cap,"compact host allocation failed");size_t at=0;for(int i=0;i<10;i++){size_t n=(size_t)counts[i];if(n&&(ce=cudaMemcpy(host+at,g.compact+(size_t)i*COMPACT_PER_CLASS,n*sizeof(*host),cudaMemcpyDeviceToHost))!=cudaSuccess){std::free(host);return fail(e,cap,"compact candidate copy",ce);}at+=n;}pr->device_to_host_bytes=sizeof(counts)+total*sizeof(*host);int ok=pp_decode_compact(host,total,score_thr,nms_thr,det);std::free(host);if(!ok)return fail(e,cap,"compact decode failed");}else{if((ce=cudaMemcpy(out->data,g.raw,g.raw_floats*4,cudaMemcpyDeviceToHost))!=cudaSuccess)return fail(e,cap,"CUDA output copy",ce);pr->device_to_host_bytes=g.raw_floats*4;}float stage=0;cudaEventElapsedTime(&stage,g.event[0],g.event[1]);pr->pfn_ms=stage;cudaEventElapsedTime(&stage,g.event[1],g.event[2]);pr->backbone_ms=stage;cudaEventElapsedTime(&stage,g.event[2],g.event[3]);pr->heads_ms=stage;pr->total_ms=hms()-begin;size_t col_spatial=use_implicit()?(size_t)128*128:(size_t)256*256,colbig_k=use_implicit()?576:3456;pr->workspace_bytes=m->data_bytes+m->data_bytes/2+(size_t)30000*20*11*4+(size_t)30000*4*4+(size_t)64*30000*4+(size_t)64*512*512*4+2*(size_t)64*256*256*4+3*(size_t)128*128*128*4+(size_t)384*128*128*4+2*(size_t)64*128*128*4+g.raw_floats*4+(size_t)576*col_spatial*sizeof(__half)+colbig_k*128*128*sizeof(__half)+(det?(size_t)10*COMPACT_PER_CLASS*sizeof(pp_compact_candidate)+10*sizeof(int32_t):0);return 1;}

extern "C" int pp_infer_cuda(const pp_model*m,const pp_pillars*p,pp_raw_output*out,pp_profile*pr,char*e,size_t cap){return infer_cuda_impl(m,p,out,nullptr,0,0,pr,e,cap);}
extern "C" int pp_infer_cuda_detect(const pp_model*m,const pp_pillars*p,pp_detections*d,float score,float nms,pp_profile*pr,char*e,size_t cap){return infer_cuda_impl(m,p,nullptr,d,score,nms,pr,e,cap);}
